// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingHQ.DataAccess;

#nullable disable

namespace ParkingHQ.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParkingHQ.Models.CarPark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DailyTariff")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarParks");
                });

            modelBuilder.Entity("ParkingHQ.Models.CarParkFloor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarParkId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarParkId");

                    b.ToTable("CarParkFloors");
                });

            modelBuilder.Entity("ParkingHQ.Models.EntryExit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntryExitType")
                        .HasColumnType("int");

                    b.Property<int>("ParkinglotId")
                        .HasColumnType("int");

                    b.Property<int?>("PermanentTenantId")
                        .HasColumnType("int");

                    b.Property<int>("carParkId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkinglotId");

                    b.HasIndex("PermanentTenantId");

                    b.HasIndex("carParkId");

                    b.ToTable("EntryExits");
                });

            modelBuilder.Entity("ParkingHQ.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarParkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarParkId");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("ParkingHQ.Models.HolidayTariffSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarParkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TariffEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TariffPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarParkId");

                    b.ToTable("HolidayTariff");
                });

            modelBuilder.Entity("ParkingHQ.Models.ParkingLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarParkFloorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPermanentTenant")
                        .HasColumnType("bit");

                    b.Property<int>("ParkinLotNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CarParkFloorId");

                    b.ToTable("ParkingLots");
                });

            modelBuilder.Entity("ParkingHQ.Models.PermanentTenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PermanentTenants");
                });

            modelBuilder.Entity("ParkingHQ.Models.PermanentTenantParkingLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastPayment")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParkingLotId")
                        .HasColumnType("int");

                    b.Property<int?>("PermanentTenantId")
                        .HasColumnType("int");

                    b.Property<int>("Pin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("PermanentTenantId");

                    b.ToTable("PermanentTenantParkingLots");
                });

            modelBuilder.Entity("ParkingHQ.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParkingLotId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLotId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("ParkingHQ.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CarParkId")
                        .HasColumnType("int");

                    b.Property<int>("ParkingLotId")
                        .HasColumnType("int");

                    b.Property<int?>("PermanentTenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CarParkId");

                    b.HasIndex("ParkingLotId");

                    b.HasIndex("PermanentTenantId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ParkingHQ.Models.WeekdayTariffSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarParkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TariffEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TariffPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CarParkId");

                    b.ToTable("WeekdayTariff");
                });

            modelBuilder.Entity("ParkingHQ.Models.CarParkFloor", b =>
                {
                    b.HasOne("ParkingHQ.Models.CarPark", null)
                        .WithMany("Floors")
                        .HasForeignKey("CarParkId");
                });

            modelBuilder.Entity("ParkingHQ.Models.EntryExit", b =>
                {
                    b.HasOne("ParkingHQ.Models.ParkingLot", "Parkinglot")
                        .WithMany()
                        .HasForeignKey("ParkinglotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingHQ.Models.PermanentTenant", "PermanentTenant")
                        .WithMany()
                        .HasForeignKey("PermanentTenantId");

                    b.HasOne("ParkingHQ.Models.CarPark", "carPark")
                        .WithMany("EntryExits")
                        .HasForeignKey("carParkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parkinglot");

                    b.Navigation("PermanentTenant");

                    b.Navigation("carPark");
                });

            modelBuilder.Entity("ParkingHQ.Models.Holiday", b =>
                {
                    b.HasOne("ParkingHQ.Models.CarPark", null)
                        .WithMany("Holidays")
                        .HasForeignKey("CarParkId");
                });

            modelBuilder.Entity("ParkingHQ.Models.HolidayTariffSection", b =>
                {
                    b.HasOne("ParkingHQ.Models.CarPark", null)
                        .WithMany("HolidayTariff")
                        .HasForeignKey("CarParkId");
                });

            modelBuilder.Entity("ParkingHQ.Models.ParkingLot", b =>
                {
                    b.HasOne("ParkingHQ.Models.CarParkFloor", null)
                        .WithMany("ParkingLots")
                        .HasForeignKey("CarParkFloorId");
                });

            modelBuilder.Entity("ParkingHQ.Models.PermanentTenantParkingLot", b =>
                {
                    b.HasOne("ParkingHQ.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingHQ.Models.PermanentTenant", null)
                        .WithMany("PermanentTenantParkingLots")
                        .HasForeignKey("PermanentTenantId");

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingHQ.Models.Ticket", b =>
                {
                    b.HasOne("ParkingHQ.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParkingLot");
                });

            modelBuilder.Entity("ParkingHQ.Models.Transaction", b =>
                {
                    b.HasOne("ParkingHQ.Models.CarPark", null)
                        .WithMany("Transactions")
                        .HasForeignKey("CarParkId");

                    b.HasOne("ParkingHQ.Models.ParkingLot", "ParkingLot")
                        .WithMany()
                        .HasForeignKey("ParkingLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ParkingHQ.Models.PermanentTenant", "PermanentTenant")
                        .WithMany()
                        .HasForeignKey("PermanentTenantId");

                    b.Navigation("ParkingLot");

                    b.Navigation("PermanentTenant");
                });

            modelBuilder.Entity("ParkingHQ.Models.WeekdayTariffSection", b =>
                {
                    b.HasOne("ParkingHQ.Models.CarPark", null)
                        .WithMany("WeekdayTariff")
                        .HasForeignKey("CarParkId");
                });

            modelBuilder.Entity("ParkingHQ.Models.CarPark", b =>
                {
                    b.Navigation("EntryExits");

                    b.Navigation("Floors");

                    b.Navigation("HolidayTariff");

                    b.Navigation("Holidays");

                    b.Navigation("Transactions");

                    b.Navigation("WeekdayTariff");
                });

            modelBuilder.Entity("ParkingHQ.Models.CarParkFloor", b =>
                {
                    b.Navigation("ParkingLots");
                });

            modelBuilder.Entity("ParkingHQ.Models.PermanentTenant", b =>
                {
                    b.Navigation("PermanentTenantParkingLots");
                });
#pragma warning restore 612, 618
        }
    }
}
